name: my_documents
description: "My Documents App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  
dependencies:
  cupertino_icons: ^1.0.8
  algoliasearch: ^1.43.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  intl: ^0.20.2
  provider: ^6.1.2
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.4
  flutter_web_auth_2: ^5.0.0-alpha.7
  retry: ^3.1.2
  smooth_page_indicator: ^1.1.0
  file_picker: ^10.3.7
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.0
  mime: ^2.0.0
  web_socket_channel: ^3.0.3
  appwrite: 20.3.2
  timeago: ^3.7.1
  video_player: ^2.10.1
  visibility_detector: ^0.4.0+2
  any_link_preview: ^3.0.3
  image_cropper: ^11.0.0
  camera: ^0.11.3
  gal: ^2.3.2
  livekit_client: ^2.6.0
  uuid: ^4.5.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  http: ^1.6.0
  pdfx: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"
